### ISSUE TITLE
Data stopped in September

### ISSUE THREAD

**Issue by gtklocker** [kargig/covid19-gr-json#3]
What would it take to revive this effort? If this process was manual until now perhaps we can try our hand at automatically extracting the data from the pdfs. [This](https://eody.gov.gr/wp-content/uploads/2020/11/covid-gr-daily-report-20201110.pdf) is the last pdf for example

**Comment by kargig** [comment]
The process was manual as the pdf format kept changing frequently.
I don't have the time to invest in automating the process right now. If someone else wants to start the effort, I'd be glad to contribute if I can

**Comment by gtklocker** [comment]
I see other parties are maintaining an up-to-date dataset that could be used for the visualisation instead. https://github.com/iMEdD-Lab/open-data
